// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctpczbxyakggbyetnubx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0cGN6Ynh5YWtnZ2J5ZXRudWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjgzODUsImV4cCI6MjA3MzE0NDM4NX0.viJj7gy5kyWbM0UjSlNqYioe15ZMW4f6NcBerhCfVPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});